#!/bin/bash

<<'CMTS'
Just a quick test/iteration file. Temporary. Anything here
may be lost at any time.
CMTS

# Testing functions return values

dummy_func() {
  arg1=$1
  arg2=$2

  if (($arg1==0 && $arg2==1));then
    echo "arg1=0 and arg2=1"
  elif (($arg1==1 && $arg2==1)) || (($arg1==2 && $arg2==2));then
      echo "11 or 22"

  fi

}


dummy_func 1 1





